name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "psycho66.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.psycho66.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.psycho66.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.psycho66.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.psycho66.web.id", custom_domain = true },
  { pattern = "support.zoom.us.psycho66.web.id", custom_domain = true },  
  { pattern = "cache.netflix.com.psycho66.web.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "3f57b0ff360045c4bbad5c8963092a0e"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "9d746e96-8bb4-434f-960d-55bcc555bb07"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/inconigto-vpn/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/inconigto-vpn/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/inconigto-vpn/refs/heads/master/web/link.html"
